### ISSUE TITLE
Codegen issues

### ISSUE THREAD

**Issue by vlad-scherbich** [Howon/Oscar#81]
1. Passing strings to functions (they don't exist natively in LLVM, how to represent?)
2. [DONE] Unable to pass types that aren't `int`s to functions, because we can't know the type of IDs until semantic analysis is finished. We can accept the argument but we don't know its type inside the function.
3. [DONE] Logical binary operators, like == or < will return 1 or 0, which means that 1 or 0 is printed as opposed to "true" or "false" in the case of println(5 == 5).
4. [DONE] We don't have bitwise ops.
5. [DONE] `if/else` branches
6. Local variable declarations (mut/immut)
7. Dealing with messages
8. Lambdas
9. List/Set/Map access/assignment
10. Actor/Pool
12. [DONE] Unable to print the result of a boolean Binop, e.g. `print(true && true)` due to crashes.

**Comment by Howon** [comment]
Priorities:

if/else branches, scoping
Local variable declarations (mut/immut)

Passing strings to functions (they don't exist natively in LLVM, how to represent?)
Unable to types that aren't ints to functions, because we can't know the type of IDs until semantic analysis is finished. We can accept the argument but we don't know its type inside the function.

Logical binary operators, like == or < will return 1 or 0, which means that 1 or 0 is printed as opposed to "true" or "false" in the case of println(5 == 5).

Dealing with messages
Lambdas
List/Set/Map access/assignment
Actor/Pool

We don't have bitwise ops.
